import os

RERANKER_CANDIDATE_MULTIPLIER = int(
    os.environ.get("RERANKER_CANDIDATE_MULTIPLIER", "5")
)
RERANKER_MAX_CANDIDATES = int(os.environ.get("RERANKER_MAX_CANDIDATES", "100"))
LLM_CONTEXT_DOCUMENTS = int(os.environ.get("LLM_CONTEXT_DOCUMENTS", "100"))
INSIGHT_CACHE_VERSION = 3
