import os


def _env(name: str, default: str) -> str:
    return os.environ.get(name, "").strip() or default


DEFAULT_LLM_PROVIDER = _env("DEFAULT_LLM_PROVIDER", "llama.cpp")
DEFAULT_LLM_MODEL = _env(
    "DEFAULT_LLM_MODEL",
    "unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL",
)
LLAMA_CPP_BASE_URL = _env("LLAMA_CPP_BASE_URL", "http://127.0.0.1:8080")
LLAMA_CPP_API_KEY = _env("LLAMA_CPP_API_KEY", "no-key")
LLAMA_CPP_SERVER_BIN = _env("LLAMA_CPP_SERVER_BIN", "llama-server")
LLAMA_CPP_STARTUP_TIMEOUT = int(_env("LLAMA_CPP_STARTUP_TIMEOUT", "180"))
LLAMA_CPP_N_GPU_LAYERS = _env("LLAMA_CPP_N_GPU_LAYERS", "auto").lower()

RERANKER_CANDIDATE_MULTIPLIER = int(
    _env("RERANKER_CANDIDATE_MULTIPLIER", "5")
)
RERANKER_MAX_CANDIDATES = int(_env("RERANKER_MAX_CANDIDATES", "240"))
LLM_CONTEXT_DOCUMENTS = int(_env("LLM_CONTEXT_DOCUMENTS", "240"))
HIERARCHICAL_RAG_BATCH_DOCUMENTS = int(
    _env("HIERARCHICAL_RAG_BATCH_DOCUMENTS", "60")
)
HIERARCHICAL_RAG_MAX_DOCUMENTS = int(
    _env("HIERARCHICAL_RAG_MAX_DOCUMENTS", "240")
)
INSIGHT_CACHE_VERSION = 10
